name: Lambda Deployer

on:

  workflow_call:
    inputs:
      component_name:
        required: true
        type: string

      version:
        required: true
        type: string

      env:
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env == 'prod' && 'Production' || inputs.env == 'staging' && 'Staging' || inputs.env == 'dev' && 'Development' }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.sha }}

      - name: Release check
        id: check_release
        run: |
          if gh release view "${{ inputs.version }}" >/dev/null 2>&1; then
            echo "Release ${{ inputs.version }} found, proceeding with deployment."
          else
            echo "Release ${{ inputs.version }} not found, aborting." >&2
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout tagged commit
        run: |
          # fetch tags so we can checkout the release tag
          git fetch --tags
          git checkout --quiet "refs/tags/${{ inputs.version }}"
          echo "Checked out tag ${{ inputs.version }} at `git rev-parse HEAD`"

      - name: Read version
        id: version
        run: |
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/gh-actions-role
          aws-region: us-west-2

      - name: Package Lambda code
        run: |
          echo "Packaging Lambda with dependencies..."
          mkdir package
          pip3 install -r requirements.txt -t package/
          cp lambda.py package/

          cd package
          zip -r ../${{ inputs.component_name }}-${{ steps.version.outputs.version }}.zip .
          cd ..

      - name: Upload Lambda package to S3
        run: |
          aws s3 cp ${{ inputs.component_name }}-${{ steps.version.outputs.version }}.zip s3://ec-lambdas-bucket/${{ inputs.env }}/${{ inputs.component_name }}-${{ steps.version.outputs.version }}.zip

      - name: Deploy CloudFormation stack
        run: |
          STACK_NAME=${{ inputs.component_name }}-${{ inputs.env }}


          if aws cloudformation describe-stacks --stack-name $STACK_NAME >/dev/null 2>&1; then

            aws cloudformation update-stack \
              --stack-name $STACK_NAME \
              --template-body file://build/cloudformation.yml \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameters \
                ParameterKey=Env,ParameterValue=${{ vars.ENV }} \
                ParameterKey=JobName,ParameterValue=${{ inputs.component_name }} \
                ParameterKey=CodeVersion,ParameterValue=${{ steps.version.outputs.version }}

            aws cloudformation wait stack-update-complete --stack-name $STACK_NAME

          else

            aws cloudformation create-stack \
              --stack-name $STACK_NAME \
              --template-body file://build/cloudformation.yml \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameters \
                ParameterKey=Env,ParameterValue=${{ vars.ENV }} \
                ParameterKey=JobName,ParameterValue=${{ inputs.component_name }} \
                ParameterKey=CodeVersion,ParameterValue=${{ steps.version.outputs.version }}

            aws cloudformation wait stack-create-complete --stack-name $STACK_NAME
          fi